// Code generated by MockGen. DO NOT EDIT.
// Source: implementation.go

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	model "github.com/hizu77/avito-autumn-2025/internal/model"
)

// UserStorage is a mock of userStorage interface.
type UserStorage struct {
	ctrl     *gomock.Controller
	recorder *UserStorageMockRecorder
}

// UserStorageMockRecorder is the mock recorder for UserStorage.
type UserStorageMockRecorder struct {
	mock *UserStorage
}

// NewUserStorage creates a new mock instance.
func NewUserStorage(ctrl *gomock.Controller) *UserStorage {
	mock := &UserStorage{ctrl: ctrl}
	mock.recorder = &UserStorageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *UserStorage) EXPECT() *UserStorageMockRecorder {
	return m.recorder
}

// SaveUsers mocks base method.
func (m *UserStorage) SaveUsers(ctx context.Context, users []model.User) ([]model.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveUsers", ctx, users)
	ret0, _ := ret[0].([]model.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SaveUsers indicates an expected call of SaveUsers.
func (mr *UserStorageMockRecorder) SaveUsers(ctx, users interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveUsers", reflect.TypeOf((*UserStorage)(nil).SaveUsers), ctx, users)
}

// TeamStorage is a mock of teamStorage interface.
type TeamStorage struct {
	ctrl     *gomock.Controller
	recorder *TeamStorageMockRecorder
}

// TeamStorageMockRecorder is the mock recorder for TeamStorage.
type TeamStorageMockRecorder struct {
	mock *TeamStorage
}

// NewTeamStorage creates a new mock instance.
func NewTeamStorage(ctrl *gomock.Controller) *TeamStorage {
	mock := &TeamStorage{ctrl: ctrl}
	mock.recorder = &TeamStorageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *TeamStorage) EXPECT() *TeamStorageMockRecorder {
	return m.recorder
}

// GetTeamByName mocks base method.
func (m *TeamStorage) GetTeamByName(ctx context.Context, name string) (model.Team, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTeamByName", ctx, name)
	ret0, _ := ret[0].(model.Team)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTeamByName indicates an expected call of GetTeamByName.
func (mr *TeamStorageMockRecorder) GetTeamByName(ctx, name interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTeamByName", reflect.TypeOf((*TeamStorage)(nil).GetTeamByName), ctx, name)
}

// SaveTeam mocks base method.
func (m *TeamStorage) SaveTeam(ctx context.Context, team model.Team) (model.Team, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveTeam", ctx, team)
	ret0, _ := ret[0].(model.Team)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SaveTeam indicates an expected call of SaveTeam.
func (mr *TeamStorageMockRecorder) SaveTeam(ctx, team interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveTeam", reflect.TypeOf((*TeamStorage)(nil).SaveTeam), ctx, team)
}
