// Code generated by go-enum DO NOT EDIT.
// Version: v0.9.2

// Built By: go install

package model

import (
	"fmt"

	"github.com/pkg/errors"
)

const (
	// StatusOpen is a Status of type open.
	StatusOpen Status = "open"
	// StatusMerged is a Status of type merged.
	StatusMerged Status = "merged"
)

var ErrInvalidStatus = errors.New("not a valid Status")

// String implements the Stringer interface.
func (x Status) String() string {
	return string(x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x Status) IsValid() bool {
	_, err := ParseStatus(string(x))
	return err == nil
}

var _StatusValue = map[string]Status{
	"open":   StatusOpen,
	"merged": StatusMerged,
}

// ParseStatus attempts to convert a string to a Status.
func ParseStatus(name string) (Status, error) {
	if x, ok := _StatusValue[name]; ok {
		return x, nil
	}
	return Status(""), fmt.Errorf("%s is %w", name, ErrInvalidStatus)
}
