// Code generated by MockGen. DO NOT EDIT.
// Source: implementation.go

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	model "github.com/hizu77/avito-autumn-2025/internal/model"
)

// UserStorage is a mock of userStorage interface.
type UserStorage struct {
	ctrl     *gomock.Controller
	recorder *UserStorageMockRecorder
}

// UserStorageMockRecorder is the mock recorder for UserStorage.
type UserStorageMockRecorder struct {
	mock *UserStorage
}

// NewUserStorage creates a new mock instance.
func NewUserStorage(ctrl *gomock.Controller) *UserStorage {
	mock := &UserStorage{ctrl: ctrl}
	mock.recorder = &UserStorageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *UserStorage) EXPECT() *UserStorageMockRecorder {
	return m.recorder
}

// UpdateActivity mocks base method.
func (m *UserStorage) UpdateActivity(ctx context.Context, id string, activity bool) (model.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateActivity", ctx, id, activity)
	ret0, _ := ret[0].(model.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateActivity indicates an expected call of UpdateActivity.
func (mr *UserStorageMockRecorder) UpdateActivity(ctx, id, activity interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateActivity", reflect.TypeOf((*UserStorage)(nil).UpdateActivity), ctx, id, activity)
}

// PullRequestStorage is a mock of pullRequestStorage interface.
type PullRequestStorage struct {
	ctrl     *gomock.Controller
	recorder *PullRequestStorageMockRecorder
}

// PullRequestStorageMockRecorder is the mock recorder for PullRequestStorage.
type PullRequestStorageMockRecorder struct {
	mock *PullRequestStorage
}

// NewPullRequestStorage creates a new mock instance.
func NewPullRequestStorage(ctrl *gomock.Controller) *PullRequestStorage {
	mock := &PullRequestStorage{ctrl: ctrl}
	mock.recorder = &PullRequestStorageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *PullRequestStorage) EXPECT() *PullRequestStorageMockRecorder {
	return m.recorder
}

// GetPullRequestsByReviewer mocks base method.
func (m *PullRequestStorage) GetPullRequestsByReviewer(ctx context.Context, id string) ([]model.PullRequest, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPullRequestsByReviewer", ctx, id)
	ret0, _ := ret[0].([]model.PullRequest)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPullRequestsByReviewer indicates an expected call of GetPullRequestsByReviewer.
func (mr *PullRequestStorageMockRecorder) GetPullRequestsByReviewer(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPullRequestsByReviewer", reflect.TypeOf((*PullRequestStorage)(nil).GetPullRequestsByReviewer), ctx, id)
}
