// Code generated by MockGen. DO NOT EDIT.
// Source: implementation.go

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	model "github.com/hizu77/avito-autumn-2025/internal/model"
)

// AdminStorage is a mock of storage interface.
type AdminStorage struct {
	ctrl     *gomock.Controller
	recorder *AdminStorageMockRecorder
}

// AdminStorageMockRecorder is the mock recorder for AdminStorage.
type AdminStorageMockRecorder struct {
	mock *AdminStorage
}

// NewAdminStorage creates a new mock instance.
func NewAdminStorage(ctrl *gomock.Controller) *AdminStorage {
	mock := &AdminStorage{ctrl: ctrl}
	mock.recorder = &AdminStorageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *AdminStorage) EXPECT() *AdminStorageMockRecorder {
	return m.recorder
}

// GetAdmin mocks base method.
func (m *AdminStorage) GetAdmin(ctx context.Context, id string) (model.Admin, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAdmin", ctx, id)
	ret0, _ := ret[0].(model.Admin)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAdmin indicates an expected call of GetAdmin.
func (mr *AdminStorageMockRecorder) GetAdmin(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAdmin", reflect.TypeOf((*AdminStorage)(nil).GetAdmin), ctx, id)
}

// InsertAdmin mocks base method.
func (m *AdminStorage) InsertAdmin(ctx context.Context, admin model.Admin) (model.Admin, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertAdmin", ctx, admin)
	ret0, _ := ret[0].(model.Admin)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// InsertAdmin indicates an expected call of InsertAdmin.
func (mr *AdminStorageMockRecorder) InsertAdmin(ctx, admin interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertAdmin", reflect.TypeOf((*AdminStorage)(nil).InsertAdmin), ctx, admin)
}
