// Code generated by MockGen. DO NOT EDIT.
// Source: implementation.go

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	model "github.com/hizu77/avito-autumn-2025/internal/model"
)

// TeamStorage is a mock of teamStorage interface.
type TeamStorage struct {
	ctrl     *gomock.Controller
	recorder *TeamStorageMockRecorder
}

// TeamStorageMockRecorder is the mock recorder for TeamStorage.
type TeamStorageMockRecorder struct {
	mock *TeamStorage
}

// NewTeamStorage creates a new mock instance.
func NewTeamStorage(ctrl *gomock.Controller) *TeamStorage {
	mock := &TeamStorage{ctrl: ctrl}
	mock.recorder = &TeamStorageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *TeamStorage) EXPECT() *TeamStorageMockRecorder {
	return m.recorder
}

// GetTeamByUserID mocks base method.
func (m *TeamStorage) GetTeamByUserID(ctx context.Context, userID string) (model.Team, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTeamByUserID", ctx, userID)
	ret0, _ := ret[0].(model.Team)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTeamByUserID indicates an expected call of GetTeamByUserID.
func (mr *TeamStorageMockRecorder) GetTeamByUserID(ctx, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTeamByUserID", reflect.TypeOf((*TeamStorage)(nil).GetTeamByUserID), ctx, userID)
}

// PullRequestStorage is a mock of pullRequestStorage interface.
type PullRequestStorage struct {
	ctrl     *gomock.Controller
	recorder *PullRequestStorageMockRecorder
}

// PullRequestStorageMockRecorder is the mock recorder for PullRequestStorage.
type PullRequestStorageMockRecorder struct {
	mock *PullRequestStorage
}

// NewPullRequestStorage creates a new mock instance.
func NewPullRequestStorage(ctrl *gomock.Controller) *PullRequestStorage {
	mock := &PullRequestStorage{ctrl: ctrl}
	mock.recorder = &PullRequestStorageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *PullRequestStorage) EXPECT() *PullRequestStorageMockRecorder {
	return m.recorder
}

// GetPullRequestByID mocks base method.
func (m *PullRequestStorage) GetPullRequestByID(ctx context.Context, id string) (model.PullRequest, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPullRequestByID", ctx, id)
	ret0, _ := ret[0].(model.PullRequest)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPullRequestByID indicates an expected call of GetPullRequestByID.
func (mr *PullRequestStorageMockRecorder) GetPullRequestByID(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPullRequestByID", reflect.TypeOf((*PullRequestStorage)(nil).GetPullRequestByID), ctx, id)
}

// InsertPullRequest mocks base method.
func (m *PullRequestStorage) InsertPullRequest(ctx context.Context, request model.PullRequest) (model.PullRequest, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertPullRequest", ctx, request)
	ret0, _ := ret[0].(model.PullRequest)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// InsertPullRequest indicates an expected call of InsertPullRequest.
func (mr *PullRequestStorageMockRecorder) InsertPullRequest(ctx, request interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertPullRequest", reflect.TypeOf((*PullRequestStorage)(nil).InsertPullRequest), ctx, request)
}

// UpdatePullRequestInfo mocks base method.
func (m *PullRequestStorage) UpdatePullRequestInfo(ctx context.Context, req model.PullRequest) (model.PullRequest, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdatePullRequestInfo", ctx, req)
	ret0, _ := ret[0].(model.PullRequest)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdatePullRequestInfo indicates an expected call of UpdatePullRequestInfo.
func (mr *PullRequestStorageMockRecorder) UpdatePullRequestInfo(ctx, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatePullRequestInfo", reflect.TypeOf((*PullRequestStorage)(nil).UpdatePullRequestInfo), ctx, req)
}

// UpdatePullRequestReviewers mocks base method.
func (m *PullRequestStorage) UpdatePullRequestReviewers(ctx context.Context, req model.PullRequest) (model.PullRequest, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdatePullRequestReviewers", ctx, req)
	ret0, _ := ret[0].(model.PullRequest)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdatePullRequestReviewers indicates an expected call of UpdatePullRequestReviewers.
func (mr *PullRequestStorageMockRecorder) UpdatePullRequestReviewers(ctx, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatePullRequestReviewers", reflect.TypeOf((*PullRequestStorage)(nil).UpdatePullRequestReviewers), ctx, req)
}
