// Code generated by go-enum DO NOT EDIT.
// Version: v0.9.2

// Built By: go install

package response

import (
	"errors"
	"fmt"
)

const (
	// CodeTeamExists is a Code of type TeamExists.
	CodeTeamExists Code = "TEAM_EXISTS"
	// CodePrExists is a Code of type PrExists.
	CodePrExists Code = "PR_EXISTS"
	// CodePrMerged is a Code of type PrMerged.
	CodePrMerged Code = "PR_MERGED"
	// CodeNotAssigned is a Code of type NotAssigned.
	CodeNotAssigned Code = "NOT_ASSIGNED"
	// CodeNoCandidate is a Code of type NoCandidate.
	CodeNoCandidate Code = "NO_CANDIDATE"
	// CodeNotFound is a Code of type NotFound.
	CodeNotFound Code = "NOT_FOUND"
	// CodeInternal is a Code of type Internal.
	CodeInternal Code = "INTERNAL"
	// CodeBadRequest is a Code of type BadRequest.
	CodeBadRequest Code = "BAD_REQUEST"
	// CodeInvalidCredentials is a Code of type InvalidCredentials.
	CodeInvalidCredentials Code = "INVALID_CREDS"
)

var ErrInvalidCode = errors.New("not a valid Code")

// String implements the Stringer interface.
func (x Code) String() string {
	return string(x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x Code) IsValid() bool {
	_, err := ParseCode(string(x))
	return err == nil
}

var _CodeValue = map[string]Code{
	"TEAM_EXISTS":   CodeTeamExists,
	"PR_EXISTS":     CodePrExists,
	"PR_MERGED":     CodePrMerged,
	"NOT_ASSIGNED":  CodeNotAssigned,
	"NO_CANDIDATE":  CodeNoCandidate,
	"NOT_FOUND":     CodeNotFound,
	"INTERNAL":      CodeInternal,
	"BAD_REQUEST":   CodeBadRequest,
	"INVALID_CREDS": CodeInvalidCredentials,
}

// ParseCode attempts to convert a string to a Code.
func ParseCode(name string) (Code, error) {
	if x, ok := _CodeValue[name]; ok {
		return x, nil
	}
	return Code(""), fmt.Errorf("%s is %w", name, ErrInvalidCode)
}
